export enum PROFILE_VALIDATION {
  SERVER_ERROR = 'SERVER_ERROR',
  NO_DATA = 'NO_DATA',
  NO_USERNAME = 'NO_USERNAME',
  NO_AGE = 'NO_AGE',
  NO_COUNTRY = 'NO_COUNTRY',
  NO_AVATAR = 'NO_AVATAR',
  TOO_SHORT_USERNAME = 'TOO_SHORT_USERNAME',
  TOO_BIG_AGE = 'TOO_BIG_AGE',
  TOO_LONG_BIO = 'TOO_LONG_BIO'
}
