name: React App CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node_modules_${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: npm run build:prod
        if: always()
      - name: Test typescript
        run: npm run test:ts
        if: always()
      - name: Lint typescript
        run: npm run lint:ts
        if: always()
      - name: Lint SCSS
        run: npm run lint:scss
